name = "notekeeper"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[[kv_namespaces]]
binding = "NOTES"
id = "f329bf44dae745c7a31d2ed5996ed179"

[env.production]
name = "notekeeper-prod"

[[env.production.kv_namespaces]]
binding = "NOTES"
id = "69db83dc707e4c7e95478a437a746631"
